### ISSUE TITLE
For web enabled PIXEL, user uploaded still images get uploaded but don't display on PIXEL

### ISSUE THREAD

**Issue by alinke** [alinke/PIXEL#7]
The original file size of the PNG on my Mac was 166 bytes and the file size on the Pi was 167 bytes. This file does display fine in the still images pane. When uploading the file, the browser shows this message but it does not go away <META HTTP-EQUIV=REFRESH CONTENT="1; URL=files/index.html">

**Comment by onebeartoe** [comment]
META HTTP-EQUIV=REFRESH
I used this type of redirect, since we do not have a JEE stack to work with :(  

This is one of the reasons I tried so hard to get PIXEL working with JEE.  Websphere Liberty Profile would provide a more elegant solution for this, but since it is not compatible (yet!) we have to roll our features sometimes.  

We likely just need to send a complete HTML document, versus just that META tag snippet.

What browser was used when you saw the browser just sit there?

**Comment by alinke** [comment]
This one on chrome 

Yes even a message telling the user what to do would be fine

**Comment by onebeartoe** [comment]
I was able to reproduce the issue in Chrome.  A complete HTML document is needed for Chrome to recognize the meta tag for refreshing to a new resource.  

Please pull the latest changes to verify a temporary fix works.

**Comment by alinke** [comment]
fixed now, thx!
